site_name: Documentação

repo_name: mdsreq-fga-unb/2022.1-Monitoramento-de-Obras
repo_url: https://github.com/mdsreq-fga-unb/2022.1-Monitoramento-de-Obras

edit_uri: ""

extra_css:
  - stylesheets/extra.css

theme:
  name: material

  logo: stylesheets/assets/images/logo-horizont.png

  favicon: stylesheets/assets/favicon.png

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb/2022.1-Monitoramento-de-Obras

nav:
  - Artefatos:
    - Início: documentation.md
    - Documento de Visão: doc_visao.md
    - Organização do Projeto: doc_org_proj.md
    - Processo de Engenharia de Requisitos: planejamento/processoER.md
    # - Custos: planejamento/custos.md
    - Riscos: planejamento/riscos.md
    - Ciclos: planejamento/ciclos.md  
    #- Documento de Arquitetura: doc_arquitetura.md
    - Requisitos: planejamento/lista_requisitos.md
    - MVP: mvp.md
    # - Planejamento:
    # - Políticas do Repositório: 
    - Entregas: entregas/entregas.md
    - Lições aprendidas: licoes_aprendidas.md
    - Como contribuir: contributing.md
    - Código de conduta: code_of_conduct.md
