site_name: Documentação

repo_name: mdsreq-fga-unb/2022.1-Monitoramento-de-Obras
repo_url: https://github.com/mdsreq-fga-unb/2022.1-Monitoramento-de-Obras

edit_uri: ""

extra_css:
  - stylesheets/extra.css

theme:
  name: material

  logo: stylesheets/assets/images/logo-horizont.png

  favicon: stylesheets/assets/favicon.png

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb/2022.1-Monitoramento-de-Obras

nav:
  - Artefatos:
      - Início: documentation.md
      #- Documento de Arquitetura: doc_arquitetura.md
      - Documento de Visão: doc_visao.md
      - Organização do Projeto: doc_org_proj.md
      - Identidade Visual: visual_id.md
      # - Planejamento:
      - Plano de Comunicação: planejamento/comunicacao.md
      - Processo de Engenharia de Requisitos: planejamento/processoER.md
      # - Custos: planejamento/custos.md
      - Riscos: planejamento/riscos.md
      - Ciclos: planejamento/ciclos.md
      - Lições aprendidas: licoes_aprendidas.md
      - Entregas: entregas/entregas.md
      # - Políticas do Repositório:
      - Como contribuir: contributing.md
      - Código de conduta: code_of_conduct.md
