site_name: Documentação

repo_name: Capita-C
repo_url: https://github.com/mdsreq-fga-unb/2022.1-Capita-C

edit_uri: ""

extra_css:
  - stylesheets/extra.css

theme:
  name: material

  logo: stylesheets/assets/images/logo-horizont.png

  favicon: stylesheets/assets/favicon.png

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb/2022.1-Capita-C

nav:
  - Artefatos:
      - Início: documentation.md
      - Entregas: entregas_conjunto.md
      - Visão: visao.md
      - Organização do Projeto: org_proj.md
      - Processo de Engenharia de Requisitos: processoER.md
      # - Custos: planejamento/custos.md
      - Riscos: riscos.md
      - Ciclos: ciclos.md
      - Documento de Arquitetura: arquitetura.md
      - Requisitos: lista_requisitos.md
      - MVP: mvp.md
      - PBB: pbb.md
      - USM: usm.md
      - Diagrama de Casos de Uso: casos_de_uso.md
      - Reuniões: reunioes.md
      # - Planejamento:
      # - Políticas do Repositório:
      - Lições aprendidas: licoes_aprendidas.md
      - Como contribuir: contributing.md
      - Código de conduta: code_of_conduct.md
