version: "3.4"

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - env/.build.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: CapitaC
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - env/.build.env
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
