# This workflow deploys mkdocs automatically to GitHub pages

name: Build mkdocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
    paths: ["docs/"]

  pull_request:
    branches: ["main"]
    paths: ["docs/"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gitPages-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Installing mkdocs and theme
      - name: Installing mkdocs
        run: pip3 install mkdocs mkdocs-material

      - run: git pull
      # Building mkdocs
      - name: Building mkdocs
        run: mkdocs build && ls

      # Deploying mkdocs to branch gh-pages
      - name: Deploying mkdocs
        run: mkdocs gh-deploy
